directory: /mnt/space/music
library: /mnt/space/music/musiclibrary.blb

import:
  write: yes
  move: yes
  resume: yes

musicbrainz:
    host: 192.168.178.37:5000
    ratelimit: 100

paths:
    albumtype:soundtrack: Soundtracks/$album/$track. $artist - $title
    comp: Compilations/$album%aunique{}/$track. $artist - $title
    singleton: Artists/$artist/non-album/$title
    default: Artists/$albumartist/$album%aunique{}/$track. $title


plugins: fetchart lyrics lastgenre discogs chroma

chroma:
  auto: yes
